# Database Configuration
spring.datasource.url=jdbc:postgresql://ep-blue-unit-avfmjdzv-pooler.c-11.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_y0W1laGUXj9P

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection Pool (HikariCP) - important for Neon
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000